export const partners = [
  {
    category: "coiffeur",
    name: "Franck Provost",
    src: "/images/logo-provost.png",
    department: "82",
    city: "Montauban",
    offer: "-50% sur la coupe homme",
  },
  {
    category: "coiffeur",
    name: "Franck Provost",
    src: "/images/logo-provost.png",
    department: "82",
    city: "Montauban",
    offer: "-50% sur la coupe homme",
  },
  {
    category: "coiffeur",
    name: "Franck Provost",
    src: "/images/logo-provost.png",
    department: "82",
    city: "Montauban",
    offer: "-50% sur la coupe homme",
  },
  {
    category: "coiffeur",
    name: "Franck Provost",
    src: "/images/logo-provost.png",
    department: "82",
    city: "Montauban",
    offer: "-50% sur la coupe homme",
  },
  {
    category: "coiffeur",
    name: "Franck Provost",
    src: "/images/logo-provost.png",
    department: "82",
    city: "Montauban",
    offer: "-50% sur la coupe homme",
  },
  {
    category: "coiffeur",
    name: "Franck Provost",
    src: "/images/logo-provost.png",
    department: "82",
    city: "Montauban",
    offer: "-50% sur la coupe homme",
  },
  {
    category: "coiffeur",
    name: "Franck Provost",
    src: "/images/logo-provost.png",
    department: "82",
    city: "Montauban",
    offer: "-50% sur la coupe homme",
  },
];
